[package]
name = "testris"
version = "0.1.0"
authors = ["sschroeder <sschroeder@edgecast.com>"]

[dependencies]
piston_window = "0.44"
toml = "0.1"
env_logger = "0.3"
log = "0.3"
rand = "0.3"
nalgebra = "0.8.2"
